#!/bin/sh
#
# Construct a basic virtual environment for the Python server

python3 -m venv venv
venv/bin/pip3 install wheel
venv/bin/pip3 install --upgrade entrance

echo
echo To run, enter ./run.py
echo
